; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32s3_reversetft]
platform = espressif32@6.6.0
board = adafruit_feather_esp32s3_reversetft
board_build.mcu = esp32s3
framework = arduino
build_flags = 
	-DSPI_FREQUENCY=27000000
upload_protocol = esptool
upload_speed = 921600
upload_flags = 
	--before=no_reset
	--after=hard_reset
lib_deps = 
	adafruit/Adafruit BusIO@^1.14.5
	SPI
	Wire
	bodmer/TFT_eSPI@^2.5.43
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	links2004/WebSockets@^2.7.3
	adafruit/Adafruit AHTX0@^2.0.6
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit Unified Sensor@^1.1.15
